services:
  askoheat-exporter:
    # build: .
    image: ghcr.io/aracloud/askoheat-prometheus-exporter:latest
    container_name: askoheat-exporter
    ports:
      - "9105:9105"
    environment:
    - ASKOHEAT_URL=http://<askoheat-ip>/_gethome.json
  restart: always
